### ISSUE TITLE
version 3.9.11 I got the following error, version 3.9.01 is fine

### ISSUE THREAD

**Issue by ravelab** [mokesmokes/titanium-android-facebook#4]
[INFO] :   dalvikvm: Failed resolving Lcom/ti/facebook/ActivityWorkerProxy; interface 3794 'Lorg/appcelerator/titanium/TiLifecycle$OnActivityResultEvent;'
[WARN] :   dalvikvm: Link of class 'Lcom/ti/facebook/ActivityWorkerProxy;' failed
[ERROR] :  JNIUtil: Couldn't find Java class: com/ti/facebook/ActivityWorkerProxy
[WARN] :   W/System.err: java.lang.NoClassDefFoundError: com/ti/facebook/ActivityWorkerProxy

**Comment by mokesmokes** [comment]
@michaelAtClearly my guess is that this is your issue: https://developers.facebook.com/bugs/1376362649302663/
For some reason, on Android installs are recorded per user account per app, while on iOS it's different.

**Comment by michaelAtClearly** [comment]
Actually the issue I was having was purely titanium/javascript related, so I didn't feel the need to post here when I figured it out.  We were using some custom window manager code in the app, so I had to go into the post-build android manifest and find which activity was actually being used as launcher activity to put into facebook's android console.

**Comment by Heavyblade** [comment]
Hello I'm using the lastest version of the module 3.20.05 for android and the recently relased of Titanium 3.5.0.GA and I see the same error:

[WARN]  dalvikvm: Link of class 'Lcom/ti/facebook/ActivityWorkerProxy;' failed
[ERROR] JNIUtil: Couldn't find Java class: com/ti/facebook/ActivityWorkerProxy
[WARN]  W/System.err: java.lang.NoClassDefFoundError: com/ti/facebook/ActivityWorkerProxy

any advise ?

**Comment by mokesmokes** [comment]
This is due to Appcelerator changing version numbers. You need to use 3.6.0 or my 3_4_M branch - it is prebuilt here: http://goo.gl/U8bB1x , see http://www.tidev.io/2014/11/20/new-facebook-modules/

**Comment by pussaaon** [comment]
Do you have a plan to make it work with stable 3.5.0.GA released ?

**Comment by mokesmokes** [comment]
@pussaaon no such plan since 3.5.0.GA for Android is almost identical to 3_4_X. Your best bet is to use my 3_4_M branch which is 3_4_X with the required changes. When 3.6.0 is ready this module will work with the standard releases.

**Comment by pussaaon** [comment]
@mokesmokes   we have some problem here, the module we are using 
https://github.com/Sitata/titanium-google-analytics/tree/master/mobile/android/dist,
the latest build requires sdk 3.5.0.GA and your module requires 3.4.X

**Comment by mokesmokes** [comment]
@pussaaon then I recommend you contact that module owner and ask him to set the minimum SDK to 3.4.2 instead of 3.5.0, or you can make this change yourself. He should do that because there really is no difference between 3.4.2 and 3.5.0.GA for Android, there is no reason the minimum should be 3.5.0 in the case of Android.

**Comment by pussaaon** [comment]
@mokesmokes  ok, thank you for your recommend
